spring.application.name=demo
# for https
server.forward-headers-strategy=framework 
spring.datasource.url=jdbc:mysql://localhost:3306/bitbridgedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=create

